# Generated by Django 4.0 on 2022-01-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True)),
                ('dt_updated', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField(null=True)),
                ('catalog_name', models.TextField(null=True)),
            ],
            options={
                'db_table': 'catalogs_data',
            },
        ),
    ]
